# template_validating_webhook.yaml
kind: Service
apiVersion: v1
metadata:
  name: template-webhook
  namespace: template
spec:
  selector:
    app: template-validating-webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: template
  labels:
    app: template-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-validating-webhook
  template:
    metadata:
      labels:
        app: template-validating-webhook
    spec:
      serviceAccountName: tsb-webhook-sa
      containers:
      - name: webhook
        image: 172.22.11.2:30500/template-validating-webhook:test
        imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
     app: template-validating-webhook
  name: tsb-webhook-sa
  namespace: template
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsb-webhook-role
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tsb-webhook-rb
subjects:
- kind: ServiceAccount
  name: tsb-webhook-sa
  namespace: template
roleRef:
  kind: ClusterRole
  name: tsb-webhook-role
  apiGroup: rbac.authorization.k8s.io