apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: template-validate-webhook
  namespace: template
webhooks:
  - name: template-validate-webhook.tmax-cloud.github.com
    admissionReviewVersions:
      - v1
    sideEffects: None
    rules:
      - operations: ["UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["templateinstances"]
    clientConfig:
      caBundle: $(cat ca.crt | base64 | tr -d '\n')
      service:
        namespace: template
        name: template-webhook
        path: "/"